### ISSUE TITLE
NameError (uninitialized constant GitosisPublicKeysController::ARCondition)

### ISSUE THREAD

**Issue by sroze** [rocket-rentals/redmine-gitosis#16]
Running the redmine-gitosis plugin on Gentoo, with thin, I get this error when I go the the "/my/public_keys" page.

`NameError (uninitialized constant GitosisPublicKeysController::ARCondition):
  vendor/plugins/redmine_gitosis/app/controllers/gitosis_public_keys_controller.rb:15:in`index'
  thin (1.2.11) lib/thin/connection.rb:84:in `pre_process'
  thin (1.2.11) lib/thin/connection.rb:82:in`catch'
  thin (1.2.11) lib/thin/connection.rb:82:in `pre_process'
  thin (1.2.11) lib/thin/connection.rb:57:in`process'
  thin (1.2.11) lib/thin/connection.rb:42:in `receive_data'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in`run_machine'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
  thin (1.2.11) lib/thin/backends/base.rb:61:in`start'
  thin (1.2.11) lib/thin/server.rb:159:in `start'
  thin (1.2.11) lib/thin/controllers/controller.rb:86:in`start'
  thin (1.2.11) lib/thin/runner.rb:185:in `send'
  thin (1.2.11) lib/thin/runner.rb:185:in`run_command'
  thin (1.2.11) lib/thin/runner.rb:151:in `run!'
  thin (1.2.11) bin/thin:6
  /usr/bin/thin:8:in`load'
  /usr/bin/thin:8`

How can I solve that?

Best regards,
Samuel.

**Comment by flyingmongoose** [comment]
I am running into this same issue, what was done to resolve this?

**Comment by Janderson** [comment]
if running redmine1.4 this solution is where 
https://projects.littlestreamsoftware.com/issues/6544#note-2
not plugin defect, but redmine deprecate lib.
Enjoy
