### ISSUE TITLE
Trying to access Public Keys via web interface

### ISSUE THREAD

**Issue by decko** [rocket-rentals/redmine-gitosis#6]
Hi guys. Sorry about use this way to contact you.
I've instaled redmine-gitosis but I don't know why it doesn't work.
Redmine report this:

Processing GitosisPublicKeysController#index (for 189.123.192.43 at 2010-05-23 15:08:49) [GET]
  Parameters: {"action"=>"index", "controller"=>"gitosis_public_keys"}

ActiveRecord::StatementInvalid (SQLite3::SQLException: no such table: gitosis_public_keys: SELECT \* FROM "gitosis_public_keys" WHERE (1=1 AND (active=1)) AND ("gitosis_public_keys".user_id = 3)  ORDER BY active DESC, created_at DESC):
  vendor/plugins/redmine_gitosis/app/controllers/gitosis_public_keys_controller.rb:17:in `index'
  /dh/passenger/lib/phusion_passenger/rack/request_handler.rb:92:in`process_request'
  /dh/passenger/lib/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:400:in`start_request_handler'
  /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:351:in `handle_spawn_application'
  /dh/passenger/lib/phusion_passenger/utils.rb:184:in`safe_fork'
  /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:349:in `handle_spawn_application'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in`**send**'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:163:in `start'
  /dh/passenger/lib/phusion_passenger/railz/application_spawner.rb:209:in`start'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  /dh/passenger/lib/phusion_passenger/abstract_server_collection.rb:126:in`lookup_or_add'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  /dh/passenger/lib/phusion_passenger/abstract_server_collection.rb:80:in`synchronize'
  /dh/passenger/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:255:in`spawn_rails_application'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  /dh/passenger/lib/phusion_passenger/spawn_manager.rb:287:in`handle_spawn_application'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in `__send__'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:352:in`main_loop'
  /dh/passenger/lib/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
## Rendering /home/amosca/projetos.amosca.inf.br/public/500.html (500 Internal Server Error)

Using redmine to create the repositorie gives the same error: "no such table"

Thanks and sorry for annoying you guys

**Comment by lars-derichter** [comment]
Have you tried running "RAILS_ENV=production rake db:migrate_plugins" from within the redmine directory?

**Comment by decko** [comment]
Thanks

**Comment by lexical-scope** [comment]
I have the same issue, and I did run the above command, below is my tail

<pre>
Processing GitosisPublicKeysController#index (for 192.168.10.195 at 2011-03-30 19:02:21) [GET]
  Parameters: {"action"=>"index", "controller"=>"gitosis_public_keys"}

ActiveRecord::StatementInvalid (RuntimeError: ERROR     C42883  M
operator does not exist: boolean = integer     H
No operator matches the given name and argument type(s). You might need to add explicit type casts.    P
59     F
parse_oper.c  L766     R
op_error: SELECT * FROM "gitosis_public_keys" WHERE (1=1 AND (active=1)) AND ("gitosis_public_keys".user_id = 1)  ORDER BY active DESC, created_at DESC):

</pre>


I'm using postgres if this matters
